"""Minimal PDB reader/writer (small molecules, first model only)."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from ..core import elements
from ..core.molecule import Molecule
from ..core.results import ParseResult
from .errors import FileFormatError


def _formal_charge(line: str) -> int:
    """Columns 79-80: a digit then a sign, as in "1+" or "2-"; usually blank."""
    field = line[78:80].strip() if len(line) >= 79 else ""
    if len(field) == 2 and field[0].isdigit() and field[1] in "+-":
        return int(field[0]) * (1 if field[1] == "+" else -1)
    if len(field) == 2 and field[1].isdigit() and field[0] in "+-":
        return int(field[1]) * (1 if field[0] == "+" else -1)
    return 0


def read(path) -> ParseResult:
    symbols, coords = [], []
    charges = []
    for line in Path(path).read_text(errors="replace").splitlines():
        if line.startswith(("ATOM  ", "HETATM")):
            try:
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
            except ValueError as exc:
                raise FileFormatError(f"{path}: bad coordinates in {line!r}") from exc
            elem = line[76:78].strip() if len(line) >= 78 else ""
            if not elem:
                name = line[12:16].strip()
                elem = "".join(ch for ch in name if ch.isalpha())
            symbols.append(elements.normalize_symbol(elem))
            coords.append([x, y, z])
            charges.append(_formal_charge(line))
        elif line.startswith("ENDMDL") and symbols:
            break
    if not symbols:
        raise FileFormatError(f"{path}: no ATOM/HETATM records found")
    # PDB has no molecular charge; it has a per-atom one that is almost
    # always blank. When some atoms do carry it, their sum is the best
    # statement of the charge the file makes.
    declared = any(charges)
    mol = Molecule(symbols, np.array(coords), title=Path(path).stem,
                   charge=sum(charges), charge_known=declared)
    return ParseResult(frames=[mol], program="PDB", source=str(path))


def write(path, molecule: Molecule) -> None:
    with open(path, "w") as fh:
        fh.write("REMARK   generated by microscope\n")
        for idx, (sym, (x, y, z)) in enumerate(zip(molecule.symbols, molecule.coords), 1):
            name = sym if len(sym) == 2 else f" {sym}"
            fh.write(
                f"HETATM{idx:5d} {name:<4s}LIG A   1    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {sym:>2s}\n"
            )
        fh.write("END\n")
