"""Minimal PDB reader/writer (small molecules, first model only)."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from ..core import elements
from ..core.molecule import Molecule
from ..core.results import ParseResult
from .errors import FileFormatError


def read(path) -> ParseResult:
    symbols, coords = [], []
    for line in Path(path).read_text(errors="replace").splitlines():
        if line.startswith(("ATOM  ", "HETATM")):
            try:
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
            except ValueError as exc:
                raise FileFormatError(f"{path}: bad coordinates in {line!r}") from exc
            elem = line[76:78].strip() if len(line) >= 78 else ""
            if not elem:
                name = line[12:16].strip()
                elem = "".join(ch for ch in name if ch.isalpha())
            symbols.append(elements.normalize_symbol(elem))
            coords.append([x, y, z])
        elif line.startswith("ENDMDL") and symbols:
            break
    if not symbols:
        raise FileFormatError(f"{path}: no ATOM/HETATM records found")
    mol = Molecule(symbols, np.array(coords), title=Path(path).stem)
    return ParseResult(frames=[mol], program="PDB", source=str(path))


def write(path, molecule: Molecule) -> None:
    with open(path, "w") as fh:
        fh.write("REMARK   generated by microscp\n")
        for idx, (sym, (x, y, z)) in enumerate(zip(molecule.symbols, molecule.coords), 1):
            name = sym if len(sym) == 2 else f" {sym}"
            fh.write(
                f"HETATM{idx:5d} {name:<4s}LIG A   1    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {sym:>2s}\n"
            )
        fh.write("END\n")
